name: Deploy to IPFS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install -g @pinata/sdk

    - name: Upload to Pinata
      env:
        PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
        PINATA_SECRET_API_KEY: ${{ secrets.PINATA_SECRET_API_KEY }}
      run: |
        npx pinata-cli upload-dir --dir ./ --pin-name "My Website"