name: Deploy index.html to Pinata

on:
  push:
    branches:
      - main
    paths:
      - "index.html"  # Run workflow only if index.html is modified

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (required for pinata-cli)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Compatible version

      # Step 3: Install pinata-cli
      - name: Install pinata-cli
        run: npm install -g pinata-cli

      # Step 4: Upload index.html to Pinata
      - name: Upload index.html to Pinata
        env:
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
          PINATA_SECRET_API_KEY: ${{ secrets.PINATA_SECRET_API_KEY }}
        run: |
          echo "Uploading index.html to Pinata..."
          CID=$(pinata-cli pinata pin index.html --name "Updated Index" | jq -r '.IpfsHash')

          # Check if upload was successful
          if [ -z "$CID" ]; then
            echo "Upload failed. Check the logs above for errors."
            exit 1
          else
            echo "Upload successful! New CID: $CID"
            echo "Access your website at: https://ipfs.io/ipfs/$CID"
          fi
