name: Deploy index.html to Pinata

on:
  push:
    branches:
      - main
    paths:
      - "index.html"

permissions:
  contents: write 

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload index.html to Pinata
        env:
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
          PINATA_SECRET_API_KEY: ${{ secrets.PINATA_SECRET_API_KEY }}
        run: |
          RESPONSE=$(curl -s -X POST "https://api.pinata.cloud/pinning/pinFileToIPFS" \
            -H "pinata_api_key: $PINATA_API_KEY" \
            -H "pinata_secret_api_key: $PINATA_SECRET_API_KEY" \
            -H "Content-Type: multipart/form-data" \
            -F "file=@index.html" \
            -F 'pinataMetadata={"name": "index.html"}')

          CID=$(echo $RESPONSE | jq -r '.IpfsHash')

          if ( "$CID" == "null" ); then
            echo "Upload failed! Response: $RESPONSE"
            exit 1
          else
            echo "Upload successful! New CID: $CID"
            echo "NEW_CID=$CID" >> $GITHUB_ENV
          fi

      - name: Update README.md with new CID
        run: |
          sed -i "s|https://ipfs.io/ipfs/[a-zA-Z0-9]*|https://ipfs.io/ipfs/$NEW_CID|" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update README with new IPFS CID: $NEW_CID" || echo "No changes to commit"
          git push
