name: Deploy index.html to Pinata

on:
  push:
    branches:
      - main
    paths:
      - "index.html"  # Run only when index.html is modified

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Upload index.html to Pinata using API
      - name: Upload index.html to Pinata
        env:
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
          PINATA_SECRET_API_KEY: ${{ secrets.PINATA_SECRET_API_KEY }}
        run: |
          echo "Uploading index.html to Pinata..."

          RESPONSE=$(curl -s -X POST "https://api.pinata.cloud/pinning/pinFileToIPFS" \
            -H "pinata_api_key: $PINATA_API_KEY" \
            -H "pinata_secret_api_key: $PINATA_SECRET_API_KEY" \
            -H "Content-Type: multipart/form-data" \
            -F "file=@index.html" \
            -F 'pinataMetadata={"name": "index.html"}')

          CID=$(echo $RESPONSE | jq -r '.IpfsHash')

          if [ "$CID" == "null" ]; then
            echo "Upload failed! Response: $RESPONSE"
            exit 1
          else
            echo "Upload successful! New CID: $CID"
            echo "Access your website at: https://ipfs.io/ipfs/$CID"
          fi
